localfunc.o:localfunc.c
	gcc -c localfunc.c
mysocket.o:mysocket.c
	gcc -c mysocket.c
LoginModule.o:LoginModule.c
	gcc -c LoginModule.c
RegisterModule.o:RegisterModule.c
	gcc -c RegisterModule.c
bianyi:localfunc.o mysocket.o LoginModule.o RegisterModule.o
clean:
	rm *.o
